https://arxiv.org/abs/2310.18724?utm_source=chatgpt.com -link_data_source  

https://drive.google.com/drive/folders/17S1VPYTyn6sKWMglWN2sb3CAfZveLGqO?  -drive_link


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

In [2]:
!pip install gdown

import gdown
import pandas as pd

file_id = "1-UuQb5ypabR2qVKd_kEu3I7OAd1mtQtz"
url = f"https://drive.google.com/uc?id={file_id}"

output = "wcld.csv"
gdown.download(url, output, quiet=False)



In [4]:
df = pd.read_csv("wcld.csv")

In [5]:
df.shape

(1476967, 54)

In [6]:
df.columns

Index(['county', 'new_id', 'sex', 'race', 'judge_id', 'case_type', 'wcisclass',
       'age_offense', 'age_judge', 'prior_felony', 'prior_misdemeanor',
       'prior_criminal_traffic', 'highest_severity', 'release', 'probation',
       'is_recid_new', 'recid_180d', 'zip', 'pct_black', 'pct_hisp',
       'pct_male', 'pct_rural', 'pct_urban', 'pct_college', 'pct_food_stamps',
       'pop_dens', 'pct_somecollege', 'med_hhinc', 'year', 'jail',
       'train_test_split_caselevel', 'train_test_split_deflevel',
       'prior_charges_severity7', 'prior_charges_severity8',
       'prior_charges_severity9', 'prior_charges_severity10',
       'prior_charges_severity11', 'prior_charges_severity12',
       'prior_charges_severity13', 'prior_charges_severity14',
       'prior_charges_severity15', 'prior_charges_severity16',
       'prior_charges_severity17', 'prior_charges_severity18',
       'prior_charges_severity19', 'prior_charges_severity20',
       'prior_charges_severity21', 'max_hist_jail', 

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1476967 entries, 0 to 1476966
Data columns (total 54 columns):
 #   Column                      Non-Null Count    Dtype  
---  ------                      --------------    -----  
 0   county                      1476967 non-null  int64  
 1   new_id                      1476967 non-null  int64  
 2   sex                         1476967 non-null  object 
 3   race                        1476967 non-null  object 
 4   judge_id                    1476967 non-null  int64  
 5   case_type                   1476967 non-null  object 
 6   wcisclass                   1471484 non-null  object 
 7   age_offense                 1476967 non-null  int64  
 8   age_judge                   1476967 non-null  int64  
 9   prior_felony                1476967 non-null  int64  
 10  prior_misdemeanor           1476967 non-null  int64  
 11  prior_criminal_traffic      1476967 non-null  int64  
 12  highest_severity            1476967 non-null  float64
 1

In [9]:
df.isnull().sum()/len(df)*100 #show precent of nulls

county                         0.000000
new_id                         0.000000
sex                            0.000000
race                           0.000000
judge_id                       0.000000
case_type                      0.000000
wcisclass                      0.371234
age_offense                    0.000000
age_judge                      0.000000
prior_felony                   0.000000
prior_misdemeanor              0.000000
prior_criminal_traffic         0.000000
highest_severity               0.000000
release                        0.000000
probation                     30.105412
is_recid_new                   4.713985
recid_180d                     8.071406
zip                            2.742377
pct_black                      0.000000
pct_hisp                       0.000000
pct_male                       0.000000
pct_rural                      0.000000
pct_urban                      0.000000
pct_college                    0.000000
pct_food_stamps                0.000000


In [10]:
import string #convert all aobject to string
columns_to_string=df.select_dtypes(include=['object'])
for col in columns_to_string:
  df[col]=df[col].astype('string')
  df[col] = df[col].str.translate(str.maketrans('', '', string.punctuation))

#### Reducing categories

In [11]:
df.county.unique(),df.county.nunique() #county name in this data shown as a number 

(array([40, 30, 67, 71, 13, 44, 41, 70, 64, 45, 51, 37, 53, 14, 29, 56, 66,
        48, 59,  7, 16, 18, 32, 61,  6, 47, 21, 27, 43, 10, 28, 58, 68, 36,
        62,  5, 65, 17, 38, 15, 46, 55, 54, 49, 11, 35, 20,  8, 69, 60, 25,
        52,  9, 33,  1, 24,  2, 50, 22, 34, 31, 19, 23, 39,  4,  3, 12, 63,
        57, 42, 26, 72]),
 72)

In [ ]:
#Convert county from number to its real name the converting is by arxiv.org
county_map = {
    1: "Adams",
    2: "Ashland",
    3: "Barron",
    4: "Bayfield",
    5: "Brown",
    6: "Buffalo",
    7: "Burnett",
    8: "Calumet",
    9: "Chippewa",
    10: "Clark",
    11: "Columbia",
    12: "Crawford",
    13: "Dane",
    14: "Dodge",
    15: "Door",
    16: "Douglas",
    17: "Dunn",
    18: "Eau Claire",
    19: "Florence",
    20: "Fond du Lac",
    21: "Forest",
    22: "Grant",
    23: "Green",
    24: "Green Lake",
    25: "Iowa",
    26: "Iron",
    27: "Jackson",
    28: "Jefferson",
    29: "Juneau",
    30: "Kenosha",
    31: "Kewaunee",
    32: "La Crosse",
    33: "Lafayette",
    34: "Langlade",
    35: "Lincoln",
    36: "Manitowoc",
    37: "Marathon",
    38: "Marinette",
    39: "Marquette",
    40: "Milwaukee",
    41: "Monroe",
    42: "Oconto",
    43: "Oneida",
    44: "Outagamie",
    45: "Ozaukee",
    46: "Pepin",
    47: "Pierce",
    48: "Polk",
    49: "Portage",
    50: "Price",
    51: "Racine",
    52: "Richland",
    53: "Rock",
    54: "Rusk",
    55: "Sauk",
    56: "Sawyer",
    57: "Shawano",
    58: "Sheboygan",
    59: "St. Croix",
    60: "Taylor",
    61: "Trempealeau",
    62: "Vernon",
    63: "Vilas",
    64: "Walworth",
    65: "Washburn",
    66: "Washington",
    67: "Waukesha",
    68: "Waupaca",
    69: "Waushara",
    70: "Winnebago",
    71: "Wood",
    72: "Menominee"
}
df["county_name"] = df["county"].map(county_map)

In [ ]:
df.county_name.value_counts()

county_name
Milwaukee    226331
Dane         114697
Racine        73376
Waukesha      65536
Brown         61749
              ...  
Lafayette      2378
Pepin          1475
Iron           1160
Florence       1027
Menominee       612
Name: count, Length: 72, dtype: int64

In [ ]:
df.is_recid_new.value_counts(),df.is_recid_new.isnull().sum()# the target value

(is_recid_new
 0.0    820739
 1.0    586604
 Name: count, dtype: int64,
 np.int64(69624))

In [ ]:
df.release.value_counts(),df.release.isna().sum()

(release
 1    975496
 0    501471
 Name: count, dtype: int64,
 np.int64(0))

In [ ]:
#Make a binary featuers
df['sex'] = df['sex'].astype('object')
df['sex'] = df['sex'].replace({'M':1,'F':0})
df.sex.unique()

array([1, 0])

In [ ]:
# convert binary features to be astype category
col_to_cat=['is_recid_new','recid_180d_violent','recid_180d','sex','release']
for col in col_to_cat:
  df[col]=df[col].astype('category')

In [ ]:
df.race.unique() #5 categories

<StringArray>
[                 'African American',                         'Caucasian',
         'Asian or Pacific Islander', 'American Indian or Alaskan Native',
                          'Hispanic']
Length: 5, dtype: string

In [ ]:
df.race=df.race.astype('category')

In [ ]:
df.case_type.unique() #3 categories

<StringArray>
['Felony', 'Misdemeanor', 'Criminal Traffic']
Length: 3, dtype: string

In [ ]:
df.case_type=df.case_type.astype('category')

In [ ]:
df.wcisclass.nunique() # 66 categories should reduce

66

In [ ]:
wcisclass=df.wcisclass.unique()
wcisclass

<StringArray>
[                  'Drug Possession',                'Disorderly Conduct',
                 'Resisting Officer',       'Operating While Intoxicated',
                            'OAROAS',                   'Criminal Damage',
           'Operate Without License',           'Drug ManufactureDeliver',
      'Operate Vehicle wout Consent',         'Receiving Stolen Property',
        'Fourth Degree Sexual Assau',                             'Theft',
                 'WeaponsExplosives',                           'Battery',
                       'Child Abuse',                      'Bail Jumping',
          'Retail Theft Shoplifting',                    'Other Homicide',
                 'Other Misdemeanor',     'Other Crimes Against Children',
   'Operate Vehicle Without Consent',             'Other Bodily Security',
                   'Unarmed Robbery',      '1st Deg Sex Assault of Child',
               'Other Drug Offenses',                            'Escape',
      '2nd 

In [ ]:
#Dictionary to replace wcisclass and reduce num category by through several main categories that will include all types of offenses
crime_mapping_full = {
    # Drug Offenses
    'Drug Possession': 'Drug Offenses',
    'Drug ManufactureDeliver': 'Drug Offenses',
    'Drug Paraphernalia': 'Drug Offenses',
    'Other Drug Offenses': 'Drug Offenses',
    # Violent Crimes
    'Battery': 'Violent Crimes',
    'SubstantialAggravated Battery': 'Violent Crimes',
    'Resisting Officer': 'Violent Crimes',
    'Disorderly Conduct': 'Violent Crimes',
    'Armed Robbery': 'Violent Crimes',
    'Unarmed Robbery': 'Violent Crimes',
    'KidnapHostageFalse Imprisonment': 'Violent Crimes',
    'Intimidate WitnessVictim': 'Violent Crimes',
    'Stalking': 'Violent Crimes',
    'Criminal Trespass': 'Violent Crimes',
    'Other Bodily Security': 'Violent Crimes',
    'WeaponsExplosives': 'Violent Crimes',
    'Escape': 'Violent Crimes',

    # Property Crimes
    'Burglary': 'Property Crimes',
    'Retail Theft Shoplifting': 'Property Crimes',
    'Receiving Stolen Property': 'Property Crimes',
    'Worthless Checks': 'Property Crimes',
    'Forgery': 'Property Crimes',
    'Other Fraud': 'Property Crimes',
    'Public Assistance Fraud': 'Property Crimes',
    'Criminal Damage': 'Property Crimes',
    'Entering Locked Vehicle': 'Property Crimes',
    'Theft': 'Property Crimes',

    # Traffic & Vehicle Offenses
    'Reckless Driving': 'Traffic & Vehicle Offenses',
    'Hit and Run': 'Traffic & Vehicle Offenses',
    'Operating While Intoxicated': 'Traffic & Vehicle Offenses',
    'Operating while intoxicated': 'Traffic & Vehicle Offenses',
    'OAROAS': 'Traffic & Vehicle Offenses',
    'Operate Without License': 'Traffic & Vehicle Offenses',
    'Operate Vehicle wout Consent': 'Traffic & Vehicle Offenses',
    'Operate Vehicle Without Consent': 'Traffic & Vehicle Offenses',
    'FleeingEluding': 'Traffic & Vehicle Offenses',
    'BAC': 'Traffic & Vehicle Offenses',

    # Public Order & Court Offenses
    'Bail Jumping': 'Public Order & Court Offenses',
    'Contempt of Court': 'Public Order & Court Offenses',
    'Perjury': 'Public Order & Court Offenses',
    'Violation of TRO': 'Public Order & Court Offenses',
    'Extradition': 'Public Order & Court Offenses',
    'Violate Occupational': 'Public Order & Court Offenses',
    'Other Public Safety Crimes': 'Public Order & Court Offenses',


    'Sex Crimes': 'Sex & Child-Related Crimes',
    'Sexual Assault': 'Sex & Child-Related Crimes',
    'Crimes Against Children': 'Sex & Child-Related Crimes',
    'Other Crimes Against Children': 'Sex & Child-Related Crimes',
    'Child Abuse': 'Sex & Child-Related Crimes',
    '2nd Deg Sex Assault of Child':'Sex & Child-Related Crimes',
    '1st Deg Sex Assault of Child':'Sex & Child-Related Crimes',
    'Fourth Degree Sexual Assau':'Sex & Child-Related Crimes',

    # Homicide & Attempted Homicide
    'First Degree Intentional Homicide': 'Homicide & Attempted Homicide',
    'First Degree Reckless Homicide': 'Homicide & Attempted Homicide',
    'Other Homicide': 'Homicide & Attempted Homicide',

    # Miscellaneous/Other Offenses
    'NonTraffic Forfeiture': 'Miscellaneous/Other Offenses',
    'Local or Unidentified Forfeiture': 'Miscellaneous/Other Offenses',
    'Gambling': 'Miscellaneous/Other Offenses',
    'Arson': 'Miscellaneous/Other Offenses',
    'Unidentified Misdemeanor': 'Miscellaneous/Other Offenses',
    'Unidentified Misdemeanor Traffic': 'Miscellaneous/Other Offenses',
    'Unidentified Felony': 'Miscellaneous/Other Offenses',
    'Unidentified Felony Traffic': 'Miscellaneous/Other Offenses',
    'Unidentified Traffic Forfeiture': 'Miscellaneous/Other Offenses',
    'Other Felony': 'Miscellaneous/Other Offenses',
    'Other Misdemeanor': 'Miscellaneous/Other Offenses',
}

In [ ]:
df['wcisclass'] = df['wcisclass'].replace(crime_mapping_full)
df.wcisclass.value_counts() #now 8 categories

wcisclass
Traffic & Vehicle Offenses       420984
Violent Crimes                   386810
Property Crimes                  226221
Drug Offenses                    190701
Public Order & Court Offenses    128872
Miscellaneous/Other Offenses      58159
Sex & Child-Related Crimes        55344
Homicide & Attempted Homicide      4393
Name: count, dtype: Int64

In [ ]:
df['wcisclass']=df['wcisclass'].astype('category')

In [ ]:
df.all_races.unique()

<StringArray>
[                          'African American',
                                  'Caucasian',
                  'African AmericanCaucasian',
                  'Asian or Pacific Islander',
         'CaucasianAsian or Pacific Islander',
         'Asian or Pacific IslanderCaucasian',
          'American Indian or Alaskan Native',
 'American Indian or Alaskan NativeCaucasian',
                                   'Hispanic',
                          'HispanicCaucasian',
 'CaucasianAmerican Indian or Alaskan Native',
                          'CaucasianHispanic',
                  'CaucasianAfrican American']
Length: 13, dtype: string

In [ ]:
#Building an array of races and reducing categories
mapping = {
    "CaucasianHispanic": ["Hispanic", "Caucasian"],
    "African American": ["African American"],
    "Caucasian": ["Caucasian"],
    "African AmericanCaucasian": ["African American", "Caucasian"],
    "Asian or Pacific Islander": ["Asian or Pacific Islander"],
    "CaucasianAsian or Pacific Islander": ["Caucasian", "Asian or Pacific Islander"],
    "American Indian or Alaskan Native": ["American Indian or Alaskan Native"],
    "American Indian or Alaskan NativeCaucasian": ["American Indian or Alaskan Native", "Caucasian"],
    "Hispanic": ["Hispanic"],
    "HispanicCaucasian": ["Hispanic", "Caucasian"],
    "CaucasianAmerican Indian or Alaskan Native": ["American Indian or Alaskan Native", "Caucasian"],
    "CaucasianAfrican American": ["African American", "Caucasian"]
}

df["all_races"] = df["all_races"].map(mapping)

In [ ]:
df.all_races.value_counts()

all_races
[Caucasian]                                       963584
[African American]                                318207
[Hispanic]                                         52974
[Hispanic, Caucasian]                              49147
[American Indian or Alaskan Native]                44453
[American Indian or Alaskan Native, Caucasian]     19952
[African American, Caucasian]                      15060
[Asian or Pacific Islander]                        11567
[Caucasian, Asian or Pacific Islander]              1261
Name: count, dtype: int64

In [ ]:
df['county_name']=df['county_name'].astype('category')

In [ ]:
df["ID"] = range(1, len(df) + 1)# make an ID to each record 

In [ ]:
df.ID.nunique()

1476967

In [ ]:
df.columns

Index(['county', 'new_id', 'sex', 'race', 'judge_id', 'case_type', 'wcisclass',
       'age_offense', 'age_judge', 'prior_felony', 'prior_misdemeanor',
       'prior_criminal_traffic', 'highest_severity', 'release', 'probation',
       'is_recid_new', 'recid_180d', 'zip', 'pct_black', 'pct_hisp',
       'pct_male', 'pct_rural', 'pct_urban', 'pct_college', 'pct_food_stamps',
       'pop_dens', 'pct_somecollege', 'med_hhinc', 'year', 'jail',
       'train_test_split_caselevel', 'train_test_split_deflevel',
       'prior_charges_severity7', 'prior_charges_severity8',
       'prior_charges_severity9', 'prior_charges_severity10',
       'prior_charges_severity11', 'prior_charges_severity12',
       'prior_charges_severity13', 'prior_charges_severity14',
       'prior_charges_severity15', 'prior_charges_severity16',
       'prior_charges_severity17', 'prior_charges_severity18',
       'prior_charges_severity19', 'prior_charges_severity20',
       'prior_charges_severity21', 'max_hist_jail', 

In [ ]:
df.age_offense.unique()# there are not real values-150 etc..

array([ 40,  39,  17,  65,  51,  55,  41,  22,  19,  18,  57,  59,  35,
        42,  23,  48,  62,  31,  20,  52,  21,  32,  16,  24,  25,  26,
        44,  36,  28,  29,  27,  38,  30,  34,  47,  50,  33,  37,  45,
        43,  49,  53,  46,  58, 128,  71,  15,  54,  63,  74,  64,  56,
        66,  67,  70,  60,  69,  68,  14,  76,  61,  73,  72,  77,  81,
        79,  75,  78,  82,  80,  86,  85, 106,  84, 130, 126,  83,  92,
        88,  89, 139,  94,  91, 138,  90,  87, 122, 150, 129, 118])

In [ ]:
df.age_judge.unique()# there are not real values-150 etc..

array([ 41,  40,  17,  65,  51,  55,  43,  24,  19,  57,  60,  36,  42,
        48,  20,  62,  31,  23,  52,  21,  32,  18,  22,  26,  45,  37,
        29,  30,  25,  35,  39,  27,  28,  34,  47,  49,  50,  53,  33,
        38,  46,  44,  16,  54,  59,  58, 128,  71,  64,  74,  56,  67,
        68,  70,  61,  63,  66,  15,  69,  77,  75,  72,  78,  73,  81,
        80,  76,  82,  83,  14,  86,  79, 106,  85, 130, 126,  93,  89,
       139,  94,  92,  84,  90,  87,  88, 122,  91, 150, 119,  95])

In [ ]:
df.jail.nunique()

953

In [ ]:
df.judge_id.nunique(),df.judge_id.isna().sum() #to check later if the same judge along the cases and if effects the judgment

(658, np.int64(0))

In [ ]:
df.highest_severity.unique()

array([ 7.,  9., 10., 11., 16., 18., 12., 13., 14., 17., 15., 20., 21.,
       19.,  8.])

In [ ]:
df=df.drop(columns='county')# after using that to get the county name there is no need

In [ ]:
df_preper.to_parquet("df_preper.parquet", index=False, compression="snappy")

In [ ]:
df_split=df[['ID','train_test_split_caselevel','train_test_split_deflevel']]

#### next to EDA

In [ ]:
df_split.to_csv('df_split.csv',index=False)